import { env } from "@/config/env";
import type { SettingListResponse, SettingRecord } from "./setting.types";

export type PublicSettings = {
  siteName: string;
  siteTagline: string;
  siteDescription: string;
  businessHours: string;
  websiteLogo: string;
  heroBannersDesktop: string[];
  heroBannersMobile: string[];
  seoTitle: string;
  seoDescription: string;
  contactPhone: string;
  whatsappUrl: string;
  contactEmail: string;
  contactAddress: string;
  facebookUrl: string;
  linkedinUrl: string;
  instagramUrl: string;
  twitterUrl: string;
};

export const defaultPublicSettings: PublicSettings = {
  siteName: "AM Management Group",
  siteTagline: "One Group. Multiple Businesses.",
  siteDescription:
    "AM Management Group - Empowering growth through diversified operations in construction, engineering, plantation, retail, and travel services.",
  businessHours: "",
  websiteLogo: "",
  heroBannersDesktop: [],
  heroBannersMobile: [],
  seoTitle: "AM Management Group",
  seoDescription: "Generated by AM Management Group",
  contactPhone: "+60 6-XXX XXXX",
  whatsappUrl: "",
  contactEmail: "info@ammanagement.com.my",
  contactAddress: "Ayer Keroh, 75450 Melaka, Malaysia",
  facebookUrl: "",
  linkedinUrl: "",
  instagramUrl: "",
  twitterUrl: "",
};

const normalizeSettingValue = (value?: string) => {
  const trimmedValue = value?.trim() ?? "";
  const markdownLinkMatch = trimmedValue.match(/^\[([^\]]+)\]\(([^)]+)\)$/);

  return markdownLinkMatch?.[2]?.trim() || trimmedValue;
};

const normalizeWhatsAppNumber = (value?: string) =>
  normalizeSettingValue(value).replace(/\D/g, "");

const buildWhatsAppUrl = (value?: string) => {
  const number = normalizeWhatsAppNumber(value);
  return number ? `https://wa.me/${number}` : "";
};

const toSettingsMap = (settings: SettingRecord[]) =>
  settings.reduce<Record<string, string>>((settingsMap, setting) => {
    settingsMap[setting.key] = normalizeSettingValue(setting.value);
    return settingsMap;
  }, {});

export const mapPublicSettings = (
  settings: SettingRecord[],
): PublicSettings => {
  const settingsMap = toSettingsMap(settings);
  const siteName = settingsMap["site.name"] || defaultPublicSettings.siteName;
  const siteDescription =
    settingsMap["site.description"] || defaultPublicSettings.siteDescription;

  return {
    siteName,
    siteTagline:
      settingsMap["site.tagline"] || defaultPublicSettings.siteTagline,
    siteDescription,
    businessHours:
      settingsMap["site.business_hours"] || defaultPublicSettings.businessHours,
    websiteLogo:
      settingsMap["site.website_logo"] || defaultPublicSettings.websiteLogo,
    heroBannersDesktop: (
      settingsMap["site.hero_banner_desktop"] ||
      settingsMap["site.hero_banner"] ||
      settingsMap["site.heru_banner"]
    )
      .split(",")
      .map((banner) => banner.trim())
      .filter(Boolean),
    heroBannersMobile: (settingsMap["site.hero_banner_mobile"] || "")
      .split(",")
      .map((banner) => banner.trim())
      .filter(Boolean),
    seoTitle: settingsMap["seo.title"] || siteName,
    seoDescription: settingsMap["seo.description"] || siteDescription,
    contactPhone:
      settingsMap["contact.phone"] || defaultPublicSettings.contactPhone,
    whatsappUrl:
      buildWhatsAppUrl(settingsMap["contact.whatsapp"]) ||
      defaultPublicSettings.whatsappUrl,
    contactEmail:
      settingsMap["contact.email"] || defaultPublicSettings.contactEmail,
    contactAddress:
      settingsMap["contact.address"] || defaultPublicSettings.contactAddress,
    facebookUrl:
      settingsMap["social.facebook"] || defaultPublicSettings.facebookUrl,
    linkedinUrl:
      settingsMap["social.linkedin"] || defaultPublicSettings.linkedinUrl,
    instagramUrl:
      settingsMap["social.instagram"] || defaultPublicSettings.instagramUrl,
    twitterUrl:
      settingsMap["social.twitter"] || defaultPublicSettings.twitterUrl,
  };
};

export const fetchPublicSettings = async (
  init?: RequestInit,
): Promise<PublicSettings> => {
  const response = await fetch(`${env.apiBaseUrl}/settings`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });

  if (!response.ok) {
    throw new Error("Failed to fetch public settings");
  }

  const result = (await response.json()) as {
    success: boolean;
    data?: SettingListResponse;
  };

  return mapPublicSettings(result.data?.settings ?? []);
};
