"use client";

import { useEffect, useState } from "react";
import { env } from "@/config/env";

export interface SettingItem {
  id: string;
  key: string;
  value: string;
  updatedAt: string;
}

export interface SettingsApiResponse {
  success: boolean;
  message?: string;
  data: {
    meta?: {
      page: number;
      limit: number;
      total: number;
      totalPage: number;
    };
    settings: SettingItem[];
  };
}

export interface PublicSettings {
  siteName: string;
  siteTagline: string;
  siteDescription: string;
  contactAddress: string;
  contactEmail: string;
  contactPhone: string;
  whatsappUrl: string;
  businessHours: string;
  websiteLogo: string;
  heroBannersDesktop: string[];
  heroBannersMobile: string[];
  facebookUrl: string;
  linkedinUrl: string;
  instagramUrl: string;
  twitterUrl: string;
  seoTitle: string;
  seoDescription: string;
  achievements: {
    title: string;
    description: string;
    items: Array<{
      value: number;
      suffix: string;
      label: string;
    }>;
  };
}

const defaultAchievements = {
  title: "OUR ACHIEVEMENTS",
  description:
    "A decade of excellence, multi-sector growth, and a strong foundation built on trust, quality, and sustainable value creation.",
  items: [
    { value: 10, suffix: "+", label: "Years of Corporate Excellence" },
    { value: 6, suffix: "+", label: "Sister Concerns & Divisions" },
    { value: 4.8, suffix: "M+", label: "Active Project Value" },
    { value: 500, suffix: "K", label: "Issued Share Capital" },
  ],
};

export const defaultPublicSettings: PublicSettings = {
  siteName: "AM Management Group",
  siteTagline: "One group. Multiple Business",
  siteDescription:
    "AM Management Group - Empowering growth through diversified operations in construction, engineering, plantation, retail, and travel services.",
  contactAddress: "Ayer Keroh, 75450 Melaka, Malaysia",
  contactEmail: "info@ammanagement.com.my",
  contactPhone: "+1 (234) 567-890",
  whatsappUrl: "",
  businessHours:
    "Monday - Friday: 8:30 AM - 5:30 PM\nSaturday: 8:30 AM - 1:00 PM",
  websiteLogo: "https://i.ibb.co.com/ynmXSkWF/Am-logo.png",
  heroBannersDesktop: [],
  heroBannersMobile: [],
  facebookUrl: "https://share.google/KnPGp0L2yGsADQPpT",
  linkedinUrl: "https://www.linkedin.com",
  instagramUrl: "",
  twitterUrl: "",
  seoTitle: "AM Management Group",
  seoDescription: "Generated by AM Management Group",
  achievements: defaultAchievements,
};

// Markdown লিংক বা অতিরিক্ত স্পেস ক্লিন করার ইউটিলিটি
const normalizeSettingValue = (value?: string) => {
  const trimmedValue = value?.trim() ?? "";
  const markdownLinkMatch = trimmedValue.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
  return markdownLinkMatch?.[2]?.trim() || trimmedValue;
};

const normalizeWhatsAppNumber = (value?: string) =>
  normalizeSettingValue(value).replace(/\D/g, "");

const buildWhatsAppUrl = (value?: string) => {
  const number = normalizeWhatsAppNumber(value);
  return number ? `https://wa.me/${number}` : "";
};

// API রেসপন্স থেকে PublicSettings অবজেক্টে ম্যাপ করা
export const mapPublicSettings = (settings: SettingItem[]): PublicSettings => {
  const map = new Map<string, string>();

  settings.forEach((item) => {
    if (item?.key) {
      map.set(item.key, normalizeSettingValue(item.value));
    }
  });

  const siteName = map.get("site.name") || defaultPublicSettings.siteName;
  const siteDescription =
    map.get("site.description") || defaultPublicSettings.siteDescription;

  const achievements = {
    title: map.get("achievements.title") || defaultAchievements.title,
    description:
      map.get("achievements.description") || defaultAchievements.description,
    items: defaultAchievements.items.map((defaultItem, index) => {
      const itemNumber = index + 1;
      const value = Number.parseFloat(
        map.get(`achievements.item${itemNumber}.value`) ?? "",
      );

      return {
        value: Number.isFinite(value) ? value : defaultItem.value,
        suffix:
          map.get(`achievements.item${itemNumber}.suffix`) ??
          defaultItem.suffix,
        label:
          map.get(`achievements.item${itemNumber}.label`) ?? defaultItem.label,
      };
    }),
  };

  return {
    siteName,
    siteTagline: map.get("site.tagline") || defaultPublicSettings.siteTagline,
    siteDescription,
    contactAddress:
      map.get("contact.address") || defaultPublicSettings.contactAddress,
    contactEmail:
      map.get("contact.email") || defaultPublicSettings.contactEmail,
    contactPhone:
      map.get("contact.phone") || defaultPublicSettings.contactPhone,
    whatsappUrl:
      buildWhatsAppUrl(map.get("contact.whatsapp")) ||
      defaultPublicSettings.whatsappUrl,
    businessHours:
      map.get("site.business_hours") || defaultPublicSettings.businessHours,
    websiteLogo:
      map.get("site.website_logo") || defaultPublicSettings.websiteLogo,
    heroBannersDesktop: (
      map.get("site.hero_banner_desktop") ||
      map.get("site.hero_banner") ||
      map.get("site.heru_banner") ||
      ""
    )
      .split(",")
      .map((banner) => banner.trim())
      .filter(Boolean),
    heroBannersMobile: (map.get("site.hero_banner_mobile") || "")
      .split(",")
      .map((banner) => banner.trim())
      .filter(Boolean),
    facebookUrl:
      map.get("social.facebook") || defaultPublicSettings.facebookUrl,
    linkedinUrl:
      map.get("social.linkedin") || defaultPublicSettings.linkedinUrl,
    instagramUrl:
      map.get("social.instagram") || defaultPublicSettings.instagramUrl,
    twitterUrl: map.get("social.twitter") || defaultPublicSettings.twitterUrl,
    seoTitle: map.get("seo.title") || siteName,
    seoDescription: map.get("seo.description") || siteDescription,
    achievements,
  };
};

export const fetchPublicSettings = async (): Promise<PublicSettings> => {
  try {
    // env API URL থাকলে সেটা ব্যবহার করবে, নতুবা রিলেটিভ পাথ ব্যবহার করবে
    const apiUrl = env?.apiBaseUrl
      ? `${env.apiBaseUrl}/settings`
      : "/api/v1/settings";

    const response = await fetch(apiUrl, {
      cache: "no-store",
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      return defaultPublicSettings;
    }

    const result: SettingsApiResponse = await response.json();

    if (!result?.success || !Array.isArray(result?.data?.settings)) {
      return defaultPublicSettings;
    }

    return mapPublicSettings(result.data.settings);
  } catch (error) {
    console.error("Failed to fetch public settings:", error);
    return defaultPublicSettings;
  }
};

let cachedSettings: PublicSettings | null = null;
let pendingSettingsRequest: Promise<PublicSettings> | null = null;
const publicSettingsUpdatedEvent = "public-settings-updated";

const loadPublicSettings = (forceRefresh = false): Promise<PublicSettings> => {
  if (cachedSettings && !forceRefresh) {
    return Promise.resolve(cachedSettings);
  }

  pendingSettingsRequest ??= fetchPublicSettings()
    .then((settings) => {
      cachedSettings = settings;
      return settings;
    })
    .finally(() => {
      pendingSettingsRequest = null;
    });

  return pendingSettingsRequest;
};

export const invalidatePublicSettings = () => {
  cachedSettings = null;

  if (typeof window !== "undefined") {
    window.dispatchEvent(new Event(publicSettingsUpdatedEvent));
  }
};

export const usePublicSettings = (): PublicSettings => {
  const [settings, setSettings] = useState<PublicSettings>(
    defaultPublicSettings,
  );

  useEffect(() => {
    let isMounted = true;

    const refreshSettings = () => {
      cachedSettings = null;

      loadPublicSettings(true)
        .then((loadedSettings) => {
          if (isMounted) {
            setSettings(loadedSettings);
          }
        })
        .catch((error) => {
          console.error("Failed to load public settings:", error);
        });
    };

    const handleSettingsUpdated = () => refreshSettings();
    const handleVisibilityChange = () => {
      if (document.visibilityState === "visible") {
        refreshSettings();
      }
    };

    window.addEventListener(publicSettingsUpdatedEvent, handleSettingsUpdated);
    document.addEventListener("visibilitychange", handleVisibilityChange);

    refreshSettings();

    return () => {
      isMounted = false;
      window.removeEventListener(
        publicSettingsUpdatedEvent,
        handleSettingsUpdated,
      );
      document.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, []);

  return settings;
};

/*
 * Keep this exported helper available for consumers that need to update settings
 * outside the admin settings screen.
 */
export const refreshPublicSettings = () => {
  cachedSettings = null;

  return loadPublicSettings(true);
};

export default usePublicSettings;
